# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaclasses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tname',
            new_name='name',
        ),
    ]
