# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaclasses', '0002_auto_20160814_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
