# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogaclasses', '0003_auto_20160829_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_classes', to='yogaclasses.Studio'),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_classes', to='yogaclasses.Teacher'),
        ),
    ]
